apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancer
spec:
  selector:
    matchLabels:
      app: balancer
  replicas: 1
  template:
    metadata:
      labels:
        app: balancer
    spec:
      containers:
      - name: balancer
        image: public.ecr.aws/f3h2t7h5/task31:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: balancer-k8s
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: balancer
