apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw
spec:
  selector:
    matchLabels:
      app: sw
  replicas: 1
  template:
    metadata:
      labels:
        app: sw
    spec:
      containers:
      - name: red
        image: public.ecr.aws/f3h2t7h5/task21
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rb-sw-srv
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sw
