apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-red
spec:
  selector:
    matchLabels:
      app: rb-red
  replicas: 1
  template:
    metadata:
      labels:
        app: rb-red
    spec:
      containers:
      - name: red
        image: public.ecr.aws/f3h2t7h5/red11111:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rb-red-srv
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rb-red
